INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('SUBJECT 1', 'CONTENT 1')
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('SUBJECT 2', 'CONTENT 2')
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('SUBJECT 3', 'CONTENT 3')
